name: Build Binary

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'dist/@5x/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
